#server:
#  port: 8090
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@172.16.131.6:1521:orcl
#    username: limit
#    password: limit
#    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sailing.oracle.mapper

logging:
  level:
    com:
      sailing:
        oracle:
          mapper: debug


app:
  id: GetOracleStru
apollo:
  meta: http://172.16.131.242:8080
  bootstrap:
    enabled: true
    namespaces: application


